#!/bin/sh
#
# sshd        Starts sshd.
#
umask 077

check() {
  echo "Checking sshd configuration..."
  
  # Make sure the ssh-keygen progam exists
  [ -f /usr/bin/ssh-keygen ] || exit 0

  # Check that the sshd_config file exists
  [ -f /etc/ssh/sshd_config ] || exit 0

  # See if need to generate the SSH1 RSA key
  if [ ! -f /etc/ssh/ssh_host_key ] \
  && grep -q "^HostKey.*host_key" /etc/ssh/sshd_config
  then
    echo Generating RSA Key...
    /usr/bin/ssh-keygen -t rsa1 -f /etc/ssh/ssh_host_key -C '' -N ''
  fi

  # See if need to generate the SSH2 RSA key
  if [ ! -f /etc/ssh/ssh_host_rsa_key ] \
  && grep -q "^HostKey.*host_rsa_key" /etc/ssh/sshd_config
  then
    echo Generating RSA Key...
    /usr/bin/ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -C '' -N ''
  fi

  # See if need to generate the SSH2 DSA key
  if [ ! -f /etc/ssh/ssh_host_dsa_key ] \
  && grep -q "^HostKey.*host_dsa_key" /etc/ssh/sshd_config
  then
    echo Generating DSA Key... \(may take awhile\)
    /usr/bin/ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -C '' -N ''
  fi

  # See if need to generate the SSH2 ECDSA key
  if [ ! -f /etc/ssh/ssh_host_ecdsa_key ] \
  && grep -q "^HostKey.*host_ecdsa_key" /etc/ssh/sshd_config
  then
    echo Generating ECDSA Key... \(may take awhile\)
    /usr/bin/ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -C '' -N ''
  fi
}                

start() {
 echo -n "Starting sshd: "
  /usr/sbin/sshd
  #/usr/sbin/sshd -f /etc/ssh/sshd_config
# touch /var/lock/sshd.lock
  echo "OK"
}  
stop() {
  echo -n "Stopping sshd: "
  killall sshd 2>/dev/null
# rm -f /var/lock/sshd.lock
  echo "OK" 
}
restart() {
  stop
  check
  start
}  

case "$1" in
  check)
    # support inetd, just check configration during init
    check
    ;;
  start)
    # always check config if running manually
    [ -z $rcS ] && check
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

