#!/bin/sh
# g_ether - init for wb40n
#
# This init only loads/unloads the hw-phy driver for a usb interface.
# Configuration is handled via helpers in /etc/network, see /e/n/i file.


# the expected iface name
USB_IF=usb0

# arg1 is device name
# arg2 is deciseconds
checkinterface() {
  decisec='busybox usleep 100000'
  let x=0
  while [ $x -lt $2 ]
  do
    grep -o "$1" /proc/net/dev 2>/dev/null && break
    echo -en . && $decisec && let x+=1
  done
  [ $x -ge $2 ] && return 1 || return 0
}

start() {
  echo -en "Enabling USB ethernet interface: "

  # load module
  modprobe g_ether 2>/dev/null \
  || { echo -e "\n  ...driver failed to load, aborted"; exit 1; }

  # find the just created interface name
  #for dev in `ls -td /sys/class/net/usb[0-9] 2>/dev/null`; do echo ${dev##*/} && break; done  
  
  # await upto 1.2s for the interface
  checkinterface $USB_IF 12 \
  || { echo -e "\n  ...driver error, interface '$USB_IF' is not usable"; exit 1; }
}

stop() {
  echo Disabling USB ethernet interface
  iptables -t nat -F
  ifconfig $USB_IF 0.0.0.0 2>/dev/null
  ifconfig $USB_IF down 2>/dev/null
  lsmod |grep -q g_ether && rmmod g_ether && echo \ \ g_ether module unloaded
}

case $1 in
  stop)
    stop
    ;;

  start)
    start
    ;;

  restart)
    stop
    start
    ;;

  *)
    echo "$0 $@ -- error"
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
