#!/bin/sh

trap "" 1
trap "" 15

PPP_SERIAL_INTERFACE_RS232=/dev/ttyS1
PPP_SERIAL_INTERFACE_USB=/dev/ttyGS0
PPP_SERIAL_RATE_RS232=921600
PPP_SERIAL_RATE_USB=921600

start() {
  echo "Starting pppd"
  modprobe g_serial
  modprobe ppp_generic
  modprobe ppp_async
  /usr/sbin/pppd \
   192.168.0.1:192.168.0.2 \
   $PPP_SERIAL_INTERFACE_RS232 \
   $PPP_SERIAL_RATE_RS232 \
    > /dev/null &
  /usr/sbin/pppd \
   connect "chat -t 0 -v CLIENT CLIENTSERVER" \
   192.168.0.1:192.168.0.2 \
   $PPP_SERIAL_INTERFACE_USB \
   $PPP_SERIAL_RATE_USB \
    > /dev/null &
}

stop() {
  echo "Stopping pppd"
  killall -9 pppd
  rmmod g_serial
  rmmod ppp_async
  rmmod crc_ccitt
  rmmod ppp_generic
  rmmod slhc
}

case "$1" in
  
  start)
    start
    ;;

  stop)
    stop
    ;;

  restart)
    stop
    start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
