#!/bin/sh 

DAEMON=/usr/sbin/proftpd
test -f $DAEMON || exit 0

trap "" 1
trap "" 15

[ ! -d /var/run/proftpd ] && mkdir /var/run/proftpd
[ ! -f /var/log/wtmp ] && touch /var/log/wtmp


start() {
  echo -n "Starting ProFTPD: "
  $DAEMON
  if [ $? != 0 ]; then
    echo "FAILED"
    exit 1
  else
    echo "done"
  fi
}

stop() {
  echo -n "Stopping ProFTPD: "
  killall proftpd
  echo "done"
}

case "$1" in
  stop)
    stop
    ;;

  start)
    start
    ;;

  restart)
    stop
    start
    ;;

  *)
    echo "Usage: $0 {stop|start|restart}"
    exit 1
    ;;
esac

exit 0
