SDCBINS_PACKAGER_PRODUCT = $(call qstrip,$(BR2_SDC_PLATFORM))
SDCBINS_PACKAGER_VERSION = $(call qstrip,$(BR2_SDCBINS_PACKAGER_VERSION))
SDCBINS_PACKAGER_SOURCE =
SDCBINS_PACKAGER_TARNAME = sdcbins-$(SDCBINS_PACKAGER_PRODUCT)-$(SDCBINS_PACKAGER_VERSION).tar.gz
SDCBINS_PACKAGER_DEPENDENCIES = sdcsdk sdccli sdcsupp
# TODO: how to handle dhd dependency?

define SDCBINS_PACKAGER_INSTALL_TARGET_CMDS
	tar -zcf $(O)/images/$(SDCBINS_PACKAGER_TARNAME) -C $(O) sdcbins
endef

$(eval $(call GENTARGETS))
$(eval $(generic-package))
