export PLATFORM = som60
export PRODUCT = ig60

export BULID_TYPE = nand60

# Have ../../common.mk copy some extra files we want in this specific build
export FILES = pmecc.bin u-boot-spl.dtb u-boot-spl-nodtb.bin u-boot.dtb \
               u-boot-nodtb.bin u-boot.its kernel-nosig.itb sw-description \
               fdtget fdtput mkimage genimage

include ../common.mk
