#!/bin/sh

if=usb0

start() {
    modprobe atmel_usba_udc
    modprobe g_ether
    modprobe nf_conntrack_ipv4
    echo 1 > /proc/sys/net/ipv4/ip_forward
    while ! grep -q $if /proc/net/dev; do
        sleep 1;
        logger "Waiting 1 sec for $if";
    done
    ip link set $if up
    ip addr add 192.168.3.1/30 brd + dev $if
    iptables -t nat -A POSTROUTING -j MASQUERADE
}

stop() {
    echo 0 > /proc/sys/net/ipv4/ip_forward
    iptables -t nat -D POSTROUTING -j MASQUERADE
    ip link set $if down
    rmmod g_ether
}

case $1 in
  stop)
    stop
    ;;

  start)
    start
    ;;

  restart)
    stop
    start
    ;;

  *)
    echo "$0 $@ -- error"
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
