#!/bin/sh
# snmpd init script
# adapted for the wb platform

test -x /usr/sbin/snmpd || exit 0
test -x /usr/sbin/snmptrapd || exit 0

# Defaults
export MIBDIRS=/usr/share/snmp/mibs

SNMPDRUN=yes
#SNMPDOPTS='-Lsd -Lf /dev/null -p /var/run/snmpd.pid 127.0.0.1'

TRAPDRUN=no
TRAPDOPTS='-Lsd -p /var/run/snmptrapd.pid'

# Reads config file (will override defaults above)
[ -r /etc/default/snmpd ] && . /etc/default/snmpd

ssd_oknodo="-o"


# Create compatibility link to old AgentX socket location
if [ "$SNMPDCOMPAT" = "yes" ]
then
  ln -sf /var/agentx/master /var/run/agentx
fi

#
case $1 in

  start)
    echo -n Starting simple network management services:
    if [ "$SNMPDRUN" == "yes" -a -f /etc/snmp/snmpd.conf ]
    then
      start-stop-daemon -q -S -x /usr/sbin/snmpd -- $SNMPDOPTS \
      && echo -n \ snmpd
    fi
    if [ "$TRAPDRUN" == "yes" -a -f /etc/snmp/snmptrapd.conf ]
    then
      sleep 1
      start-stop-daemon -q -S -x /usr/sbin/snmptrapd -- $TRAPDOPTS \
      && echo -n \ snmptrapd
    fi
    echo 
    ;;
    
  stop)
    echo -n Stopping simple network management services:
    start-stop-daemon -q -K $ssd_oknodo -x /usr/sbin/snmpd \
    && echo -n \ snmpd
    start-stop-daemon -q -K $ssd_oknodo -x /usr/sbin/snmptrapd \
    && echo -n \ snmptrapd
    echo
    ;;
    
  restart)
    $0 stop
    $0 start
    ;;

  reload)
    echo -n Reloading simmple network management services:
    if [ "$SNMPDRUN" == "yes" -a -f /etc/snmp/snmpd.conf ]
    then
      start-stop-daemon -q -K -s 1 -p /var/run/snmpd.pid -x /usr/sbin/snmpd \
      && echo -n \ snmpd
    fi
    echo
    ;;

  *)
    echo "Usage: $0 {start|stop|restart|reload|reload}"
    exit 1
esac

exit 0
