#!/bin/sh
# gadget serial init


case "$1" in
  stop)
    /sbin/rmmod g_serial
    ;;

  start)
    /sbin/modprobe g_serial
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
