export PLATFORM = summit_supplicant
export PRODUCT = summit_supplicant-arm-eabihf

export BULID_TYPE = pkg

include ../common.mk

BR2_DL_DIR ?= ../../archive

all:
	cp latest/$(PRODUCT).tar.bz2 $(BR2_DL_DIR)/$(PRODUCT)-$(LAIRD_RELEASE_STRING).tar.bz2
