#!/bin/sh 

tftpd=/usr/bin/tftpd
trap "" 1 15
test -f $tftpd || { echo "$tftpd missing"; exit 1; }
[ ! -d /var/run/tftpd ] && mkdir -p /var/run/tftpd
[ ! -f /var/log/wtmp ] && touch /var/log/wtmp

case "$1" in
  stop)
    echo "Stopping tftp daemon"
    killall tftpd 2>/dev/null
    ;;

  start)
    echo "Starting tftp daemon"
    $tftpd
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  check)
    ;;
    
  *)
    echo "Usage: $0 {stop|start|restart}"
    exit 1
    ;;
esac

exit 0
