msd-x86 msd50n wb50n_rdvk reg50n reglwb reglwb5 mfg60n-arm-eabi mfg60n-x86 wb50n_legacy som60 som60sd som60sd_mfg bdimx6 backports firmware sterling_supplicant-x86 sterling_supplicant-arm sterling_supplicant-src lrd-network-manager-src summit_supplicant-arm-eabi summit_supplicant-x86 linux-docs summit_supplicant-arm-eabihf:
	make -C $@ all

.PHONY: msd-x86 sterling_supplicant-x86 sterling_supplicant-arm lrd-network-manager-src linux-docs\
	sterling_supplicant-src wb50n_rdvk reg50n reglwb reglwb5 mfg60n-arm-eabi mfg60n-x86 wb50n_legacy msd50n bdimx6 som60 som60sd som60sd_mfg backports firmware
.PHONY: summit_supplicant-arm-eabi summit_supplicant-x86 summit_supplicant-arm-eabihf
