msd45n msd-x86 msd50n wb50n_rdvk reg45n reg50n reglwb reglwb5 mfg60n mfg60n-x86 wb45n_legacy wb50n_legacy bdimx6 backports firmware sterling_supplicant-x86 sterling_supplicant-arm sterling_supplicant-src lrd-network-manager-src:
	make -C $@ all

.PHONY: msd45n msd-x86 sterling_supplicant-x86 sterling_supplicant-arm lrd-network-manager-src\
	sterling_supplicant-src wb50n_rdvk reg45n reg50n reglwb reglwb5 mfg60n \
	wb45n_legacy wb50n_legacy msd50n bdimx6 backports firmware
