#!/bin/sh

# check if already have run/set
if [ -f /tmp/scan_and_set_country ]
then
    #logger "We have already set the country. Exiting."
    exit
fi

# only continue if the global profile country code is set to worldwide
profile_domain=$( sed -n '/RegDomain/s/RegDomain=//p' /etc/summit/profiles.conf 2>/dev/null )
if [ "$profile_domain" != "3" ]
then
    logger profile domain not set to world wide.  Not setting country.
    exit
fi

# look for a country code in any of the beacons, use the first we see
country=$( iw dev wlan0 scan |sed -n '/SSID/d;/Country/{s/.*try: \([A-Z0-9]*\)[\t ]*.*/\1/p;q}' )
if [ -z "$country" ]
then
    logger "No country code found."
    exit
fi

# only do once per boot
echo "$country" >/tmp/scan_and_set_country

if wl country "$country"
then
  logger "Country set to: `wl country`"
else
  logger "Setting country to: $country failed"
fi
