#!/bin/sh

# only continue if the global profile country code is set to worldwide
profile_domain=`grep RegDomain /etc/summit/profiles.conf 2>/dev/null |cut -d= -f2`
if [ ! "${profile_domain##*=}" == "3" ]; then
    logger profile domain not set to world wide.  Not setting country.
    exit
fi

# look for a country code in any of the beacons, use the first we see
country=`iw dev eth1 scan | grep Country | head -n 1 | awk '{print $2}'`
if [ -z "$country" ]; then
    logger "No country code found. Exiting."
    exit
fi

# Only do it once per boot
if [ -f /tmp/scan_and_set_country ]; then
    logger "We have already set the country. Exiting."
    exit
fi
touch /tmp/scan_and_set_country

logger "Setting country to: $country"
wl country "$country"
logger "Country set to: `wl country`"

